name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker build
        run: docker build -t my-nginx-image .
      
      - name: Docker run
        run: docker run -d -p 8080:8080 my-nginx-image

      - name: Run test.sh
        run: |
          curl -o script.sh https://github.com/LeThom2/May-Hackathon/blob/main/test.sh
          chmod +x test.sh
          ./test.sh
          exit_code=$?
          echo "Exit code: $exit_code"

