name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Dockerfile linter
      - name: Install hadolint
        run: |
          curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
          chmod +x hadolint

      - name: Lint Dockerfile
        run: |
          sleep 10
          /usr/bin/hadolint Dockerfile

      # Shell linter 
      - name: Install shellcheck
        run: sudo apt-get install shellcheck -y

      - name: Lint Shell Script
        run: shellcheck your-script.sh

      # Build
      - name: Docker build
        run: docker build -t my-nginx-image .
      
      # Run
      - name: Docker run 
        id: run-container
        run: |
          container_id=$(docker run -d -p 80:80 --name my-nginx-container my-nginx-image)
          echo "::set-output name=container_id::$container_id"

      # Test
      - name: Test Nginx server
        run: |
          sleep 5
          docker container ls
          wget -O test.sh https://raw.githubusercontent.com/LeThom2/May-Hackathon/main/test.sh
          chmod +x test.sh
          ./test.sh
          exit_code=$?
          echo "Exit code: $exit_code"
          exit $exit_code