name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker build
        run: docker build -t my-nginx-image .
      
      - name: Docker run
        id: run-container
        run: |
          container_id=$(docker run -d -p 8080:8080 my-nginx-image)
          echo "::set-output name=container_id::$container_id"
          --name my-nginx-container my-nginx-image

      - name: Get container ID
        run: |
          echo "Container ID: ${{ steps.run-container.outputs.container_id }}"

      - name: Test Nginx server
        run: |
          docker container ls
          wget -O test.sh https://raw.githubusercontent.com/LeThom2/May-Hackathon/main/test.sh
          chmod +x test.sh
          ./test.sh
          exit_code=$?
          echo "Exit code: $exit_code"
          exit $exit_code
