name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: https://raw.githubusercontent.com/LeThom2/May-Hackathon/main/*

        - name: Run ShellCheck
          uses: azohra/shell-linter@latest
          with:
            path: "https://raw.githubusercontent.com/LeThom2/May-Hackathon/main/*"