name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create environment file
        run: echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform -chdir=./terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=./terraform plan -out=tfplan
          echo "::set-output name=plan_path::tfplan"

      - name: Show Terraform Plan
        run: cat ${{ steps.plan.outputs.plan_path }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
