name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Docker build
        run: docker build -t my-nginx-image .
      
      - name: Docker run
        id: run-container
        run: |
          container_id=$(docker run -d -p 80:8080 my-nginx-image)
          echo "::set-output name=container_id::$container_id"

      - name: Get container ID
        run: |
          echo "Container ID: ${{ steps.run-container.outputs.container_id }}"

      - name: Test Nginx server
        run: |
          docker container ls
          docker exec ${{ steps.run-container.outputs.container_id }} /bin/bash -c "if curl --output /dev/null --silent --fail http://localhost:8080;
          then echo 'Nginx server is running and accessible.'; 
          else echo 'Failed to access Nginx server.'; 
          fi"

