name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build
      - name: Docker build
        run: docker build -t my-nginx-image .
      
      # Run
      - name: Docker run 
        id: run-container
        run: |
          container_id=$(docker run -d -p 80:80 --name my-nginx-container my-nginx-image)
          echo "::set-output name=container_id::$container_id"

      # Test
      - name: Test Nginx server
        run: |
          sleep 5
          docker container ls
          wget -O test.sh https://raw.githubusercontent.com/LeThom2/May-Hackathon/main/test.sh
          chmod +x test.sh
          ./test.sh
          exit_code=$?
          echo "Exit code: $exit_code"
          exit $exit_code